#pragma once

#define GEMSGUI_VERSION "3.11.1"
#define GEMSGUI_VERSION_HASH "774c9e0f"
#define GEMSGUI_GIT_BRANCH "test_arm"
#define GEMSGUI_OSX "Linux"
#define GEMSGUI_COMPILER_ID "GNU"
#define GEMSGUI_COMPILER_VERSION "13.3.0"
#define GEMSGUI_QT_VERSION "6.10.2"
