name: GEMSGUI

channels:
  - conda-forge
  - defaults

dependencies:
  - gxx_linux-64  # [linux]
  - cmake
  - ninja # [unix]
  - make  # [win]
  - 7zip  # [win]
  - git
  - ccache  # [unix]
  #- gems3k>=4.4.0
  #- thermofun>=0.4.3
  - cppzmq
  - mesa-libgl-devel-cos7-x86_64 # [unix]
  - qt6-main=6.8.2
  - qt6-charts=6.8.2
  - eigen=3.4.0
  - nlohmann_json
  - spdlog
  - python>=3.7
  - pytest
