name: GEMSGUI

channels:
  - conda-forge
  - defaults

dependencies:
  - cmake
  - git
  - gxx_linux-64  # [linux]
  - make  # [unix]
  - ninja
  - 7zip  # [win]
  #- gems3k>=4.4.0
  - thermofun>=0.4.3
  - cppzmq
  - mesa-libgl-devel-cos7-x86_64 # [unix]
  - qt6-main=6.8.2
  - qt6-charts=6.8.2
  - spdlog
  - pybind11
  - pip
  - python>=3.7
  - pytest
