name: GEMSGUI

channels:
  - conda-forge
  - defaults

dependencies:
  # Cross-platform dependencies
  - cmake
  - git
  - ninja
  - 7zip 
  - gems3k>=4.5.2
  - cppzmq
  - qt6-main=6.10.2 
  - qt6-charts=6.10.2 
  - python>=3.10
  - pytest

  # Linux compilers and tools
  - gcc_linux-64                  # [linux] 
  - gxx_linux-64                  # [linux] 
  - sysroot_linux-64              # [linux] 
  - mesa-libgl-devel-conda-x86_64 # [linux]
  - make                          # [linux]

  # macOS compilers and tools (Apple Silicon)
  - clang_osx-arm64               # [osx]
  - clangxx_osx-arm64             # [osx]
  - make                          # [osx]

  # Windows compilers and tools
  - compilers                     # [win]
