name: GEMSGUI

channels:
  - conda-forge

dependencies:
  - cmake
  - git
  - gxx_linux-64  # [linux]
  - make  # [unix]
  - ninja
  - 7zip  # [win]
  - gems3k>=4.4.0
  - thermofun>=0.4.3
  - cppzmq
  - mesa-libgl-devel-cos7-x86_64 # [unix]
  - qt=6.7.2
  - spdlog
