#!/bin/sh

# system directory of GEM
# this helps to find HTML-documentation and
# default DataBase  and Profile
# if this variable is not set
# it defaults to "/usr/lib/GEMS"

export GEMS_DIR=~/test/GEMS.sys

# user directory of GEM
# this helps to find 
# DataBase  and Profiles
# if this variable is not set
# it defaults to "~/GEM"

export GEMS_USERDIR=~/test/GEMS

# HTML-documentation browser
# currently supported:
# netscape, kfmclient (KDE), lynx (text-mode)
# if browser is not in the PATH
# here should be absolute path given
# NOTE: obsolete with QT-2.0 and later

export HTML_BROWSER=/opt/netscape/netscape

# executing GEM and
# passing parameters

exec ./gem $1 $2 $3 $4 $5
