/**********************************************************************
 
	--- Qt Architect generated file ---
 
	File: LoadMessageData.cpp
	Last generated: Wed Sep 13 16:33:45 2000
 
	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.
 
 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "LoadMessageData.h"

#include <qpushbutton.h>

LoadMessageData::LoadMessageData(QWidget *parent, const char *name)
        : QDialog(parent, name, FALSE, 0)
{
    pLabel = new QLabel(this, "Label_1");
    pLabel->setGeometry(20, 10, 350, 30);
    pLabel->setMinimumSize(0, 0);
    pLabel->setMaximumSize(32767, 32767);
    {
        QFont font("System", 10, 75, FALSE);
        font.setStyleHint((QFont::StyleHint)5);
        font.setCharSet((QFont::CharSet)1);
        pLabel->setFont( font );
    }
    pLabel->setFocusPolicy(QWidget::NoFocus);
    pLabel->setBackgroundMode(QWidget::PaletteBackground);
    pLabel->setBackgroundOrigin( QWidget::WidgetOrigin );
    pLabel->setFrameStyle( 0 );
    pLabel->setLineWidth( 1 );
    pLabel->setMidLineWidth( 0 );
    pLabel->setMargin( 0 );
    pLabel->setTextFormat( Qt::AutoText );
    pLabel->setText( "Loading Chemical System Profile " );
    pLabel->setAlignment( AlignHCenter|AlignVCenter|ExpandTabs );
    pLabel->setIndent( 0 );

    pProgress = new QProgressBar(100, this, "ProgressBar_1");
    pProgress->setGeometry(20, 50, 360, 30);
    pProgress->setMinimumSize(0, 0);
    pProgress->setMaximumSize(32767, 32767);
    pProgress->setFocusPolicy(QWidget::NoFocus);
    pProgress->setBackgroundMode(QWidget::PaletteBackground);
    pProgress->setBackgroundOrigin( QWidget::WidgetOrigin );
    pProgress->setFrameStyle( 51 );
    pProgress->setLineWidth( 2 );
    pProgress->setMidLineWidth( 0 );
    pProgress->setMargin( 0 );
    pProgress->setProgress( 1 );
    pProgress->setCenterIndicator( TRUE );
    pProgress->setIndicatorFollowsStyle( TRUE );

    QPushButton *qtarch_PushButton_1 = new QPushButton(this, "PushButton_1");
    qtarch_PushButton_1->setGeometry(150, 100, 100, 30);
    qtarch_PushButton_1->setMinimumSize(0, 0);
    qtarch_PushButton_1->setMaximumSize(32767, 32767);
    {
        QFont font("System", 8, 75, FALSE);
        font.setStyleHint((QFont::StyleHint)5);
        font.setCharSet((QFont::CharSet)1);
        qtarch_PushButton_1->setFont( font );
    }
    qtarch_PushButton_1->setFocusPolicy(QWidget::TabFocus);
    qtarch_PushButton_1->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_PushButton_1->setBackgroundOrigin( QWidget::WidgetOrigin );
    qtarch_PushButton_1->setText( "&Cancel" );
    qtarch_PushButton_1->setAutoRepeat( FALSE );
    qtarch_PushButton_1->setToggleButton( FALSE );
    qtarch_PushButton_1->setDefault( FALSE );
    qtarch_PushButton_1->setAutoDefault( FALSE );
    connect(qtarch_PushButton_1, SIGNAL(clicked()), SLOT(reject()));

    resize(400,150);
    setMinimumSize(0, 0);
    setMaximumSize(32767, 32767);
}

LoadMessageData::~LoadMessageData()
{}
