/**********************************************************************
 
	--- Qt Architect generated file ---
 
	File: LoadMessageData.h
	Last generated: Wed Sep 13 16:33:45 2000
 
	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.
 
 *********************************************************************/

#ifndef LoadMessageData_included
#define LoadMessageData_included

#include <qdialog.h>
#include <qlabel.h>
#include <qprogressbar.h>

class LoadMessageData : public QDialog
{
    Q_OBJECT

public:

    LoadMessageData(QWidget *parent = NULL, const char *name = NULL);

    virtual ~LoadMessageData();

protected:

    QLabel *pLabel;
    QProgressBar *pProgress;
};

#endif // LoadMessageData_included
