
if(USE_QT6)
  find_package(Qt6 COMPONENTS Core Gui Widgets Charts Concurrent PrintSupport Svg Help Sql REQUIRED)
endif()

if(NOT Qt6_FOUND)
  find_package(Qt5 COMPONENTS Core Gui Widgets Charts Concurrent PrintSupport Svg Help Sql REQUIRED)
endif()

if(NOT Qt6_FOUND AND NOT Qt5_FOUND)
  message(FATAL_ERROR "Package Qt6 or Qt5 required, but not found!")
endif()

if(Qt6_FOUND)
  set(GEMS_QT_TARGETS Qt6::Widgets Qt6::Core Qt6::Gui Qt6::PrintSupport Qt6::Charts Qt6::Svg Qt6::Help Qt6::Sql)
  include_directories(${Qt6Core_INCLUDE_DIRS})
  include_directories(${Qt6Gui_INCLUDE_DIRS})
  include_directories(${Qt6Widgets_INCLUDE_DIRS})
  include_directories(${Qt6PrintSupport_INCLUDE_DIRS})
  include_directories(${Qt6Svg_INCLUDE_DIRS})
  include_directories(${Qt6Concurrent_INCLUDE_DIRS})
  include_directories(${Qt6Help_INCLUDE_DIRS})
  include_directories(${Qt6Sql_INCLUDE_DIRS})
elseif(Qt5_FOUND)
  set(GEMS_QT_TARGETS Qt5::Widgets Qt5::Core Qt5::Gui Qt5::PrintSupport Qt5::Charts Qt5::Svg Qt5::Help Qt5::Sql)
  include_directories(${Qt5Core_INCLUDE_DIRS})
  include_directories(${Qt5Gui_INCLUDE_DIRS})
  include_directories(${Qt5Widgets_INCLUDE_DIRS})
  include_directories(${Qt5PrintSupport_INCLUDE_DIRS})
  include_directories(${Qt5Svg_INCLUDE_DIRS})
  include_directories(${Qt5Concurrent_INCLUDE_DIRS})
  include_directories(${Qt5Help_INCLUDE_DIRS})
  include_directories(${Qt5Sql_INCLUDE_DIRS})
endif()
