find_package(GEMS3K REQUIRED)
if(NOT GEMS3K_FOUND)
   message(FATAL_ERROR "GEMS3K library not found")
else()
   message(STATUS "Found GEMS3K v${GEMS3K_VERSION}")
endif()


if(USE_THERMOFUN MATCHES ON)
  find_package(ThermoFun REQUIRED)
  if(NOT ThermoFun_FOUND)
    message(FATAL_ERROR "ThermoFun library not found")
  else()
    message(STATUS "Found ThermoFun v${ThermoFun_VERSION}")
  endif()

  find_package(ChemicalFun REQUIRED)
  if(NOT ChemicalFun_FOUND)
    message(FATAL_ERROR "ChemicalFun library not found")
  else()
    message(STATUS "Found ChemicalFun v${ChemicalFun_VERSION}")
  endif()

endif()

if(USE_SPDLOG_PRECOMPILED)
 if(NOT TARGET spdlog::spdlog)
    find_package(spdlog CONFIG REQUIRED)
    if(NOT spdlog_FOUND)
       message(FATAL_ERROR "spdlog library not found")
    else()
       message(STATUS "Found spdlog v${spdlog_VERSION}")
    endif()
  endif()
endif()

if(USE_QT6)
  find_package(Qt6 COMPONENTS Core Gui Widgets Charts Concurrent PrintSupport Svg Help Sql REQUIRED)
endif()

if(NOT Qt6_FOUND)
  find_package(Qt5 COMPONENTS Core Gui Widgets Charts Concurrent PrintSupport Svg Help Sql REQUIRED)
endif()

if(NOT Qt6_FOUND AND NOT Qt5_FOUND)
  message(FATAL_ERROR "Package Qt6 or Qt5 required, but not found!")
endif()

if(Qt6_FOUND)
  set(GEMS_QT_TARGETS Qt6::Widgets Qt6::Core Qt6::Gui Qt6::PrintSupport Qt6::Charts Qt6::Svg Qt6::Help Qt6::Sql)
  include_directories(${Qt6Core_INCLUDE_DIRS})
  include_directories(${Qt6Gui_INCLUDE_DIRS})
  include_directories(${Qt6Widgets_INCLUDE_DIRS})
  include_directories(${Qt6PrintSupport_INCLUDE_DIRS})
  include_directories(${Qt6Svg_INCLUDE_DIRS})
  include_directories(${Qt6Concurrent_INCLUDE_DIRS})
  include_directories(${Qt6Help_INCLUDE_DIRS})
  include_directories(${Qt6Sql_INCLUDE_DIRS})
elseif(Qt5_FOUND)
  set(GEMS_QT_TARGETS Qt5::Widgets Qt5::Core Qt5::Gui Qt5::PrintSupport Qt5::Charts Qt5::Svg Qt5::Help Qt5::Sql)
  include_directories(${Qt5Core_INCLUDE_DIRS})
  include_directories(${Qt5Gui_INCLUDE_DIRS})
  include_directories(${Qt5Widgets_INCLUDE_DIRS})
  include_directories(${Qt5PrintSupport_INCLUDE_DIRS})
  include_directories(${Qt5Svg_INCLUDE_DIRS})
  include_directories(${Qt5Concurrent_INCLUDE_DIRS})
  include_directories(${Qt5Help_INCLUDE_DIRS})
  include_directories(${Qt5Sql_INCLUDE_DIRS})
endif()
