name: deploy-windows
on:
  push:
    branches:
      - help_generation_ci
  release:
    types:
      - published

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ windows-latest ]
        conda_platform: [ win-64 ]
        artifact_name: [ gemsgui-windows ]

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from CMakeLists.txt
        id: get_version
        uses: DarwinInnovation/cmake-project-version-action@v1.0

      - name: Set deploy name
        id: strings
        shell: bash
        run: >
          echo "deploy-name=GEMS${{ steps.get_version.outputs.version }}" >> "$GITHUB_OUTPUT"

      - name: Set deploy dir
        id: strings2
        shell: bash
        run: |
          echo "deploy-output-dir=${{ github.workspace }}/${{ steps.strings.outputs.deploy-name }}/Gems3-app" >> "$GITHUB_OUTPUT"
          echo "deploy-output-name=windows-${{ steps.strings.outputs.deploy-name }}.zip" >> "$GITHUB_OUTPUT"

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          channels: conda-forge, defaults
          channel-priority: true

      - name: Configuring Conda Environment
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda config --add channels conda-forge
          conda install conda-devenv
          conda devenv

      - name: Check run
        run: |
          conda activate GEMSGUI
          cd C:/Miniconda/envs/GEMSGUI/Library/lib/qt6/bin
          ls
          cd ${{ github.workspace }}/Resources/doc/html
          C:\Miniconda\envs\GEMSGUI\Library\lib\qt6\qhelpgenerator.exe -v
          C:\Miniconda\envs\GEMSGUI\Library\lib\qt6\qhelpgenerator.exe gems3helpconfig.qhcp -o gems3help.qhc
          ls
          cp -r "${{ github.workspace }}/Resources" ${{ steps.strings2.outputs.deploy-output-dir }}
          cp "${{ github.workspace }}/Resources/rungems3.bat" "${{ github.workspace }}/${{ steps.strings.outputs.deploy-name }}"
          cp "${{ github.workspace }}/Resources/README-windows.txt" "${{ github.workspace }}/${{ steps.strings.outputs.deploy-name }}/README.txt"


