name: deploy-windows
on:
  push:
    branches:
      - deploy1
  release:
    types:
      - published

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os:
          - windows-latest
        include:
          - os: windows-latest
            conda_platform: win-64
            artifact_name: gemsgui-windows

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Timestamp  # Idea from https://tinyurl.com/47wz7vpv
        id: timestamp
        shell: cmake -P {0}
        run: |
          string(TIMESTAMP current_date "%Y-%m-%d" UTC)
          message("::set-output name=now::${current_date}")

      - name: Set deploy dir
        id: strings
        shell: bash
        run: >
          echo "deploy-output-dir=${{ github.workspace }}/deploy-windows" >> "$GITHUB_OUTPUT"

      - name: Set deploy dir
        id: strings2
        shell: bash
        run: >
          echo "deploy-output-name=gemsgui-windows-${{ github.sha }}-${{ steps.timestamp.outputs.now }}.zip" >> "$GITHUB_OUTPUT"

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          channels: conda-forge, defaults
          channel-priority: true

      - name: Configuring Conda Environment
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda config --add channels conda-forge
          conda install conda-devenv
          conda devenv


      - name: Check deploy
        run: |
          cd C:/Miniconda/envs/GEMSGUI/Library/bin
          ls
          cd C:/Miniconda/envs/GEMSGUI/Library
          ls

      - name: Zipping files and folders
        shell: cmd
        run: |
              7z a "lib_bin.zip" "bin"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
            name: windows-bin
            path: lib_bin.zip

